name: Deploy update on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '15'
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Set up and deploy to Vercel
      run: |
        echo "Y" | vercel --prod ./client
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
